name: Behavioral-Cloning-2
channels:
  - defaults
  - conda-forge
  - menpo
dependencies:
  - asn1crypto=1.4.0=py_0
  - blas=1.0=mkl
  - bzip2=1.0.8
  - ca-certificates=2020.12.8
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.11.5
  - click=7.1.2=py_0
  - cloudpickle=1.6.0=py_0
  - cryptography=2.3.1
  - cycler=0.10.0
  - dask-core=2.6.0=py_0
  - decorator=4.4.2=py_0
  - eventlet=0.23.0=py35_0
  - ffmpeg=4.0
  - flask=1.1.2=py_0
  - flask-socketio=3.0.1=py35_0
  - freetype=2.8
  - greenlet=0.4.15
  - h5py=2.8.0
  - hdf5=1.10.2
  - idna=2.10=py_0
  - imageio=2.1.2=py35_0
  - intel-openmp=2019.4
  - itsdangerous=1.1.0=py_0
  - jinja2=2.11.2=py_0
  - jpeg=9b
  - kiwisolver=1.0.1
  - libcxx
  - libffi=3.2.1
  - libiconv=1.16
  - libopus=1.3.1
  - libpng=1.6.37
  - libtiff
  - markupsafe=1.0
  - matplotlib=2.2.2
  - mkl=2018.0.3=1
  - networkx=2.4=py_1
  - olefile=0.46=py35_0
  - openssl=1.0.2u
  - pandas=0.22.0
  - patsy=0.5.1=py_0
  - pip=20.3.3=pyhd8ed1ab_0
  - pycparser=2.20=py_2
  - pyopenssl=18.0.0=py35_0
  - pyparsing=2.4.7=py_0
  - python=3.5.2=5
  - python-dateutil=2.8.1=py_0
  - python-engineio=3.0.0=py_0
  - python-socketio=3.0.0=py_0
  - pytz=2020.4=pyhd3eb1b0_0
  - pywavelets=1.0.0
  - scikit-image=0.14.0
  - scikit-learn=0.20.0
  - seaborn=0.9.0=py35_0
  - setuptools=40.4.3=py35_0
  - six=1.15.0=py_0
  - sqlite=3.13.0
  - statsmodels=0.9.0=py35_0
  - tk=8.5.19
  - toolz=0.11.1=py_0
  - tornado=5.1.1
  - werkzeug=1.0.1=py_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - bleach==1.5.0
    - chardet==3.0.4
    - configobj==5.0.6
    - future==0.18.2
    - html5lib==0.9999999
    - imageio-ffmpeg==0.4.2
    - importlib-metadata==2.1.1
    - keras==2.0.9
    - markdown==3.2.2
    - moviepy==1.0.3
    - numpy==1.18.5
    - opencv-python==4.4.0.42
    - pillow==7.2.0
    - proglog==0.1.9
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - python-gnupg==0.4.6
    - python-ldap==3.3.1
    - pyyaml==5.3.1
    - requests==2.25.0
    - scipy==1.4.1
    - systematic==4.8.7
    - tensorflow==1.3.0
    - tensorflow-tensorboard==0.1.8
    - tqdm==4.54.1
    - urllib3==1.26.2
    - zipp==1.2.0
